// Plugin permissions/mobile bindings are generated by tauri-plugin, not tauri-build.
const COMMANDS: &[&str] = &["ping", "execute"];

fn main() {
  tauri_plugin::Builder::new(COMMANDS)
    .android_path("android")
    .ios_path("ios")
    .build();
}
